const { DataTypes, Model } = require('sequelize')

class MelhorEnvio extends Model {
    static init(sequelize) {
        super.init(
            {
                code: {
                    type: DataTypes.TEXT,
                    allowNull: false,
                    validate: {
                        notEmpty: {
                            msg: `Enter the code generated by the email`,
                        },
                    },
                },
                token: {
                    type: DataTypes.TEXT,
                    validate: {
                        notEmpty: `Token cannot be null`,
                    },
                },
                refreshToken: {
                    type: DataTypes.TEXT,
                    validate: {
                        notEmpty: `refreshToken cannot be null`,
                    },
                },
                active: {
                    type: DataTypes.BOOLEAN,
                    allowNull: false,
                    validate: {
                        notEmpty: {
                            msg: `The active field cannot be empty`,
                        },
                    },
                },
                token_expires: {
                    type: DataTypes.DATE,
                    validate: {
                        notEmpty: {
                            msg: `The active field cannot be empty`,
                        },
                    },
                },
            },
            { sequelize }
        )
    }

    static associate(models) {
        this.belongsTo(models.User, { foreignKey: 'user_id', as: 'user' })
    }
}

module.exports = MelhorEnvio
